import api from './axios'
export const getAdminDashboard = () => api.get('/admin/dashboard')
export const getAllUsers = () => api.get('/admin/users')
export const getAllOwners = () => api.get('/admin/owners')
export const getAllBookings = () => api.get('/admin/bookings')
export const getAllPayments = () => api.get('/admin/payments')
export const getAllFeedbacks = () => api.get('/admin/feedbacks')
export const approveOwner = (ownerId) => api.put(`/admin/owner/approve/${ownerId}`)
export const rejectOwner = (ownerId) => api.put(`/admin/owner/reject/${ownerId}`)
export const getAllComplaints = () => api.get('/admin/complaints')
export const getAllMessages = () => api.get('/admin/messages')
export const sendMessageToOwner = (data) => api.post('/admin/send-message-owner', data)
export const sendFireAlert = (data) => api.post('/admin/fire-alert', data)
export const sendParkingFullAlert = (data) => api.post('/admin/parking-full-alert', data)
